# Base site for WordPress mode (REST/sitemap/HTML)
wordpress_base: "https://exploreplasticsurgery.com"

# PubMed author query (kept broad on purpose)
pubmed_author_query: "Eppley BL[Author]"

# YouTube channel URLs for metadata (flat playlist via yt-dlp)
# Replace with the channels you want to include. Examples below:
youtube_channel_urls:
  - "https://www.youtube.com/@EppleyPlasticSurgery"   # example
  - "https://www.youtube.com/@barryeppley"            # example