# ---- WordPress ----
wordpress_base: "https://exploreplasticsurgery.com"

# ---- Identity / name variants (used by multiple sources) ----
names:
  - "Barry L. Eppley"
  - "Barry Eppley"
  - "Eppley BL"

# ---- PubMed ----
pubmed_author_query: "Eppley BL[Author]"

# ---- YouTube channels (metadata only; add/remove as needed) ----
youtube_channel_urls:
  - "https://www.youtube.com/@EppleyPlasticSurgery"    # example; replace/keep
  - "https://www.youtube.com/@barryeppley"             # example; replace/keep

# ---- OpenAlex (optional direct author IDs if you have them) ----
# openalex_author_ids:
#   - "A1969203143"   # example id; leave commented if unknown

# ---- ClinicalTrials.gov terms (broad to catch variants) ----
clinicaltrials_terms:
  - "\"Barry Eppley\""
  - "Eppley Barry"
  - "Eppley"