name: Auto-merge on Label

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    if: github.event.label.name == 'automerge' && github.event.pull_request.head.ref == 'bot/scrape'
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-merge (merge commit)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          PR=${{ github.event.pull_request.number }}
          # enable auto-merge using gh CLI (merge commit strategy; change to --squash if preferred)
          gh pr merge "$PR" --merge --auto