name: Build Status JSON (site)

on:
  workflow_dispatch: {}
  schedule:
    # Twice daily (adjust as you like)
    - cron: "20 7 * * *"
    - cron: "50 19 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate status.json
        run: |
          python tools/make_status_json.py

      - name: Commit status.json (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/status.json
          git diff --quiet && echo "No changes" || git commit -m "chore: update output/status.json"
          git push