name: Collect & Build

on:
  workflow_dispatch:
  schedule:
    - cron: "35 6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4 lxml

      - name: Export env
        env:
          NCBI_EMAIL: ${{ vars.NCBI_EMAIL }}
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: |
          echo "NCBI_EMAIL=${NCBI_EMAIL}" >> $GITHUB_ENV
          echo "YT_API_KEY=${YT_API_KEY}" >> $GITHUB_ENV

      - name: Run collectors
        run: python main.py

      - name: Enrich fulltext & build corpus
        run: |
          python tools/enrich_fulltext.py
          python tools/make_corpus.py

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.csv output/*.jsonl output/expanded/* || true
          git commit -m "Update outputs (collect + enrich + corpus)" || echo "No changes"
          git push
