name: Build & Deploy Eppley Collector (GitHub Pages)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "15 10 * * *"  # ~03:15 AZ

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run collectors
        env:
          EMAIL: ${{ vars.NCBI_EMAIL }}            # <— set this in Repo Settings → Actions → Variables
          YT_API_KEY: ${{ secrets.YT_API_KEY }}     # <— set if you want YouTube API path
        run: |
          set -e
          python main.py

      - name: Enrich PubMed abstracts (optional but recommended)
        env:
          EMAIL: ${{ vars.NCBI_EMAIL }}
          NCBI_TOOL: eppley-collector
        run: |
          if [ -f tools/augment_pubmed_abstracts.py ]; then
            python tools/augment_pubmed_abstracts.py
          fi

      - name: Merge to master
        run: |
          python tools/generate_master_csv.py
          head -n 3 output/eppley_master.csv || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
