name: Run Eppley Scraper (Resumable, Chunked, Safe)

on:
  schedule:
    - cron: "0 3 * * *"
    - cron: "0 5 * * *"
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: eppley-scraper
  cancel-in-progress: true

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 420
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install dependencies
        env: { PIP_DISABLE_PIP_VERSION_CHECK: "1" }
        run: pip install -r requirements.txt

      # WordPress chunks
      - name: WP chunk 1
        run: python main.py --only wp --wp-mode auto --wp-max 600 --save-every 150 --delay 3.0
      - name: Commit chunk 1
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "WP chunk 1 $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push

      - name: WP chunk 2
        run: python main.py --only wp --wp-mode auto --wp-max 600 --save-every 150 --delay 3.0
      - name: Commit chunk 2
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "WP chunk 2 $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push

      # APIs
      - run: python main.py --only pubmed
      - run: python main.py --only crossref
      - run: python main.py --only openalex
      - run: python main.py --only ct
      - run: python main.py --only orcid
      - run: python main.py --only yt

      # Merge & final commit
      - name: Merge publications
        run: python merge_publications.py
      - name: Final commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Auto-update scraped data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push

      - name: Upload partial output on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: partial-output
          path: output/**