name: Run Eppley Scraper

on:
  schedule:
    - cron: "0 3 * * *"   # runs every night at 03:00 UTC
  workflow_dispatch:      # gives you a 'Run workflow' button

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper
        run: python main.py --only all
      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Auto-update scraped data $(date)" || echo "No changes to commit"
          git push
